/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.PhieuNhapSachBLL;
import static DAL.Database.conectionJDBC;
import DAL.PhieuNhapSachDAL;
import DTO.NXBDTO;
import DTO.PhieuNhapSachDTO;
import DAL.Database;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import sun.security.krb5.internal.rcache.AuthList;

/**
 *
 * @author sam
 */
public class quanliphieunhapsach extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form quanliphieunhapsach
     */
    public quanliphieunhapsach() {
        initComponents();
        this.setDefaultPhieuMuon();
        this.BThemVaoPhieuTam.addActionListener(this);
        this.BThemPhieu.addActionListener(this);
        this.BXoaPhieu.addActionListener(this);
        this.BSuaPhieu.addActionListener(this);
        this.CBBNXB.removeAllItems();
        new PhieuNhapSachDAL().DoDuLieuVaoCBBNXB(this.CBBNXB);
        this.TablePhieuNhap.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TablePhieuNhap.rowAtPoint(evt.getPoint());
                TextMaNhap.setText((String) TablePhieuNhap.getValueAt(row, 0));
                TextTenSach.setText((String) TablePhieuNhap.getValueAt(row, 1));
                TextSL.setText(String.valueOf(TablePhieuNhap.getValueAt(row, 2)) );
                TextDonGia.setText(String.valueOf(TablePhieuNhap.getValueAt(row, 3)));
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                // set formatter to use UTC (instead of JVM default timezone)
                sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
                try {
                    // parse it as midnight (no shift to 01:00)
                    java.util.Date date = sdf.parse((String) TablePhieuNhap.getValueAt(row, 4));
                    java.util.Date dateutil = new java.util.Date(date.getTime());
                    DateNgayGiao.setDate(dateutil);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }
                TextMaNV.setText((String) TablePhieuNhap.getValueAt(row, 5));
                for(int i=0;i<CBBNXB.getItemCount();i++){
                   NXBDTO nxb=(NXBDTO) CBBNXB.getSelectedItem();
                    System.out.println(TablePhieuNhap.getValueAt(row, 6));
                   if(nxb.getMaNXB().equals(TablePhieuNhap.getValueAt(row, 6))){
                       return;
                   }else{
                        int index=CBBNXB.getSelectedIndex();
                        if(index+1==CBBNXB.getItemCount()){
                            CBBNXB.setSelectedIndex(0);
                        }else{
                        CBBNXB.setSelectedIndex(i+1);
                        }
                   }
                }
                    
            }
        });
        this.TablePhieuTam.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TablePhieuTam.rowAtPoint(evt.getPoint());
                DefaultTableModel model = (DefaultTableModel) TablePhieuTam.getModel();
                model.removeRow(row);
                TablePhieuTam.setModel(model);
//        int col = jTable1.columnAtPoint(evt.getPoint());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextMaNhap = new javax.swing.JTextField();
        TextTenSach = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePhieuNhap = new javax.swing.JTable();
        TextSL = new javax.swing.JTextField();
        CBBNXB = new javax.swing.JComboBox<>();
        TextDonGia = new javax.swing.JTextField();
        TextMaNV = new javax.swing.JTextField();
        BThemVaoPhieuTam = new javax.swing.JButton();
        DateNgayGiao = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePhieuTam = new javax.swing.JTable();
        BThemPhieu = new javax.swing.JButton();
        BXoaPhieu = new javax.swing.JButton();
        BSuaPhieu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHIẾU NHẬP SÁCH\n\n");

        TextMaNhap.setEditable(false);

        TablePhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(TablePhieuNhap);

        CBBNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BThemVaoPhieuTam.setText("Thêm vào phiếu tạm");

        TablePhieuTam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sách", "Số lượng", "Đơn giá", "Nhà xuất bản"
            }
        ));
        jScrollPane2.setViewportView(TablePhieuTam);

        BThemPhieu.setText("Thêm");

        BXoaPhieu.setText("Xóa");

        BSuaPhieu.setText("Sửa");

        jLabel1.setText("Mã phiếu nhập");

        jLabel3.setText("Tên sách");

        jLabel4.setText("Số lượng");

        jLabel6.setText("Nhà xuất bản");

        jLabel7.setText("Ngày giao");

        jLabel5.setText("Mã nhân viên");

        jLabel8.setText("Đơn giá");

        jLabel9.setText("Danh sách nhập sách tạm thời");

        jLabel10.setText("Danh sách phiếu nhập");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextSL, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                            .addComponent(TextTenSach)
                                            .addComponent(TextMaNhap))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BThemVaoPhieuTam))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(CBBNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TextDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                                .addGap(158, 158, 158))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DateNgayGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BThemPhieu)
                        .addGap(18, 18, 18)
                        .addComponent(BXoaPhieu)
                        .addGap(18, 18, 18)
                        .addComponent(BSuaPhieu)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BThemPhieu)
                            .addComponent(BXoaPhieu)
                            .addComponent(BSuaPhieu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TextMaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BThemVaoPhieuTam))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBBNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateNgayGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TextDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanliphieunhapsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanliphieunhapsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanliphieunhapsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanliphieunhapsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanliphieunhapsach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSuaPhieu;
    private javax.swing.JButton BThemPhieu;
    private javax.swing.JButton BThemVaoPhieuTam;
    private javax.swing.JButton BXoaPhieu;
    private javax.swing.JComboBox<String> CBBNXB;
    private com.toedter.calendar.JDateChooser DateNgayGiao;
    private javax.swing.JTable TablePhieuNhap;
    private javax.swing.JTable TablePhieuTam;
    private javax.swing.JTextField TextDonGia;
    private javax.swing.JTextField TextMaNV;
    private javax.swing.JTextField TextMaNhap;
    private javax.swing.JTextField TextSL;
    private javax.swing.JTextField TextTenSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    void setDefaultPhieuMuon(){
        DefaultTableModel model=new DefaultTableModel();
        String[] title={"Mã phiếu mượn","Tên sách","Số lượng","Đồng Giá","Ngày Giao","Mã nhân viên","Mã nhà xuất bản"};
        model.setColumnIdentifiers(title);
        ArrayList<PhieuNhapSachDTO> ar=new PhieuNhapSachBLL().getAllPhieu();
        for(int i=0;i<ar.size();i++){
            PhieuNhapSachDTO pn=ar.get(i);
            String maphieu=pn.getMaPhieu();
            String tensach=pn.getTenSach();
            int soluong=pn.getSL();
            int donggia=pn.getDongGia();
            String ngaygiao=pn.getNgayGiao();
            String manv=pn.getMaNV();
            String manxb=pn.getMaNXB();
            Object[]temp={maphieu,tensach,soluong,donggia,ngaygiao,manv,manxb};
            model.addRow(temp);
        }
        this.TablePhieuNhap.setModel(model);
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource().equals(BThemVaoPhieuTam)){
            String strDate = new SimpleDateFormat("dd-MM-yyyy").format(new java.sql.Date(this.DateNgayGiao.getDate().getTime()));
            NXBDTO nxb=(NXBDTO) CBBNXB.getSelectedItem();
            PhieuNhapSachDTO pn=new PhieuNhapSachDTO(null, this.TextTenSach.getText(), Integer.parseInt(this.TextSL.getText()), Integer.parseInt(this.TextDonGia.getText()), strDate, this.TextMaNV.getText(), nxb.getMaNXB());
            Object[]temp={pn.getTenSach(),pn.getSL(),pn.getDongGia(),pn.getMaNXB()};
            DefaultTableModel model=(DefaultTableModel) this.TablePhieuTam.getModel();
            model.addRow(temp);
            this.TablePhieuTam.setModel(model);
            
        }
        if(ae.getSource().equals(BThemPhieu)){
            String ma=DAL.Database.TaoMa("phieunhap");
            for(int i=0;i<this.TablePhieuTam.getRowCount();i++){
                String strDate = new SimpleDateFormat("dd-MM-yyyy").format(new java.sql.Date(this.DateNgayGiao.getDate().getTime()));
            new PhieuNhapSachBLL().ThemPhieuNhap(new PhieuNhapSachDTO(ma, (String) this.TablePhieuTam.getValueAt(i, 0), (int) this.TablePhieuTam.getValueAt(i, 1), (int )this.TablePhieuTam.getValueAt(i, 2), strDate, this.TextMaNV.getText(),(String) this.TablePhieuTam.getValueAt(i, 3)));
//                String sql="INSERT INTO PHIEUNHAPSACH VALUES(?,?,?,?,?,?,?)";
//                try {
//                    PreparedStatement st=conectionJDBC().prepareStatement(sql);
//                    st.setString(1, ma);
//                    st.setString(2, (String) this.TablePhieuTam.getValueAt(i, 0));
//                    st.setInt(3, Integer.parseInt((String) this.TablePhieuTam.getValueAt(i, 1)));
//                    st.setInt(4, Integer.parseInt((String) this.TablePhieuTam.getValueAt(i, 2)));
//                    st.setString(5, (String) this.TablePhieuTam.getValueAt(i, 3));
//                    st.executeUpdate();
//                } catch (SQLException ex) {
//                    Logger.getLogger(quanliphieunhapsach.class.getName()).log(Level.SEVERE, null, ex);
//                }
                this.setDefaultPhieuMuon();
            }
        }
        if(ae.getSource().equals(BXoaPhieu)){
            new PhieuNhapSachBLL().XoaPhieuNhap((String) this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 0));
                this.setDefaultPhieuMuon();
        }
        if(ae.getSource().equals(BSuaPhieu)){
            String strDate = new SimpleDateFormat("dd-MM-yyyy").format(new java.sql.Date(this.DateNgayGiao.getDate().getTime()));
            new PhieuNhapSachBLL().SuaPhieuNhap((String)this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 0), new PhieuNhapSachDTO((String)this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 0), this.TextTenSach.getText(), Integer.parseInt(this.TextSL.getText()), Integer.parseInt(this.TextDonGia.getText()), strDate, this.TextMaNV.getText(), ((NXBDTO)CBBNXB.getSelectedItem()).getMaNXB()),(String)this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 1));
            this.setDefaultPhieuMuon();
        }
    }
}
